import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { Container } from "@/components/Container";
import { SECTION_PADDING } from "@/lib/tokens";
import { cn } from "@/lib/utils";
import { getReportById } from "@/lib/checker/report";
import { FullReport } from "@/components/checker/report/FullReport";

/**
 * The uuid is the only key — unguessable, so no login is required, but
 * anyone holding the link can read it. That's the deliberate model (same
 * as a shared Google Doc link), which is exactly why getReportById's own
 * column allowlist never selects email/ip_hash/visitor_id — see that
 * file's comment. noindex/nofollow here AND in robots.ts's disallow list:
 * these are customer documents, not content to be discovered or indexed.
 */
export async function generateMetadata({ params }: { params: Promise<{ id: string }> }): Promise<Metadata> {
  const { id } = await params;
  const report = await getReportById(id);
  if (!report) return { robots: { index: false, follow: false } };

  const title = `AI Visibility Report — ${report.businessName}`;
  return {
    title,
    description: `AI Visibility Report for ${report.businessName}, generated by Boost Web Digital.`,
    robots: { index: false, follow: false },
  };
}

export default async function CheckerReportPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const report = await getReportById(id);
  if (!report) notFound();

  return (
    <>
      <div className="print:hidden">
        <Navbar />
      </div>
      <main>
        <section className={cn("relative overflow-hidden", SECTION_PADDING.default)}>
          <Container size="prose">
            <FullReport report={report} />
          </Container>
        </section>
      </main>
      <div className="print:hidden">
        <Footer />
      </div>
    </>
  );
}
